CREATE TABLE IF NOT EXISTS interactions(
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    action_weight NUMERIC(3, 2) NOT NULL CHECK (action_weight BETWEEN 0.0 AND 1.0),
    UNIQUE (event_id, user_id)
);

CREATE TABLE IF NOT EXISTS similariries(
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    event_a BIGINT NOT NULL,
    event_b BIGINT NOT NULL,
    score NUMERIC(3, 2) NOT NULL CHECK (score BETWEEN 0.0 AND 1.0),
    UNIQUE (event_a, event_b)
);
