syntax = "proto3";

package stats.service.dashboard;

import "stats/messages/analyzer/request/similar_events_request.proto";
import "stats/messages/analyzer/request/user_predictions_request.proto";
import "stats/messages/analyzer/request/interactions_count_request.proto";

import "stats/messages/analyzer/response/recommended_event.proto";

option java_package = "ru.practicum.ewm.stats.proto";

service RecommendationsController {

  // Получить рекомендации для пользователя
  rpc GetRecomendationsForUser (stats.messages.analyzer.UserRecommendationsRequestProto)
      returns (stream stats.messages.analyzer.RecommendedEventProto);

  // Получить похожие по мероприятиям
  rpc GetSimilarEvents (stats.messages.analyzer.SimilarEventsRequestProto)
      returns (stream stats.messages.analyzer.RecommendedEventProto);

  // Получить количество взаимодействий
  rpc GetInteractionsCount (stats.messages.analyzer.InteractionsCountRequestProto)
      returns (stream stats.messages.analyzer.RecommendedEventProto);
}
