CREATE TABLE IF NOT EXISTS stats (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app       VARCHAR(255) NOT NULL,
    uri       VARCHAR(512) NOT NULL,
    ip        VARCHAR(45)  NOT NULL,
    hit_timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL
    );

CREATE INDEX IF NOT EXISTS idx_endpoint_hits_stats ON stats(hit_timestamp, uri, ip);