server:
  port: 8761

spring:
  main:
    banner-mode: off
    log-startup-info: false
  jackson:
    serialization.INDENT_OUTPUT: true
  application:
    name: discovery-server

eureka:
  client:
    webclient:
      enabled: true
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    root: info
    org:
      springframework: error

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus, info, mappings