spring:
  sql.init:
    mode: ALWAYS
    schema-locations: classpath:schema-postgres.sql
  jackson:
    serialization.INDENT_OUTPUT: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6542/ewm-stats
    username: dbuser
    password: 12345
  jpa:
    generate-ddl: false
    hibernate.ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
