package ru.practicum.ewm.stats.aggregator.util;

import java.util.List;
import java.util.Locale;

/**
 * GENERATED BY DEEPSEEK</br>
 * Утилита для рендеринга матриц в виде Unicode-таблиц для логирования.
 */
@SuppressWarnings("StringRepeatCanBeUsed")
public final class TableRenderer {

	private TableRenderer() {
	}

	/**
	 * Заглушка для пустой таблицы.
	 */
	public static final String EMPTY_TABLE = """
			╔══════════╗
			║ is empty ║
			╚══════════╝
			""";

	/**
	 * Рендерит таблицу с Unicode-рамками.
	 * Угловая ячейка (левый верхний угол) всегда пустая.
	 *
	 * @param title       заголовок таблицы (может быть null)
	 * @param columnNames заголовки столбцов (без левого служебного столбца)
	 * @param rowNames    заголовки строк
	 * @param values      значения: values.get(i).get(j) — ячейка для i-й строки и j-го столбца
	 *                    (null или отсутствие — пустая ячейка)
	 * @return готовая строка таблицы
	 */
	public static String renderTable(String title,
	                                 List<String> columnNames,
	                                 List<String> rowNames,
	                                 List<List<String>> values) {

		// Если нет ни строк, ни столбцов — возвращаем заглушку
		if (columnNames.isEmpty() && rowNames.isEmpty()) {
			return EMPTY_TABLE;
		}

		// Ширина левого служебного столбца — по максимальной длине имён строк
		int rowColWidth = rowNames.stream()
				.mapToInt(String::length)
				.max()
				.orElse(0);

		// Ширины столбцов
		int[] colWidths = new int[columnNames.size()];
		for (int j = 0; j < columnNames.size(); j++) {
			int headerLen = columnNames.get(j).length();
			int maxValueLen = 0;
			for (List<String> row : values) {
				if (j < row.size()) {
					String v = row.get(j);
					if (v != null && v.length() > maxValueLen) {
						maxValueLen = v.length();
					}
				}
			}
			colWidths[j] = Math.max(headerLen, maxValueLen);
		}

		StringBuilder sb = new StringBuilder();
		if (title != null && !title.isEmpty()) {
			sb.append("\n").append(title).append("\n");
		}

		// Верхняя граница
		sb.append("╔").append("═".repeat(rowColWidth + 2)).append("╦");
		for (int j = 0; j < columnNames.size(); j++) {
			sb.append("═".repeat(colWidths[j] + 2));
			sb.append(j < columnNames.size() - 1 ? "╦" : "╗");
		}
		sb.append("\n");

		// Заголовок: угловая ячейка пустая
		sb.append("║ ").append(padRight("", rowColWidth)).append(" ║");
		for (int j = 0; j < columnNames.size(); j++) {
			sb.append(" ").append(padRight(columnNames.get(j), colWidths[j])).append(" ║");
		}
		sb.append("\n");

		// Разделитель
		sb.append("╠").append("═".repeat(rowColWidth + 2)).append("╬");
		for (int j = 0; j < columnNames.size(); j++) {
			sb.append("═".repeat(colWidths[j] + 2));
			sb.append(j < columnNames.size() - 1 ? "╬" : "╣");
		}
		sb.append("\n");

		// Строки данных
		for (int i = 0; i < rowNames.size(); i++) {
			sb.append("║ ").append(padRight(rowNames.get(i), rowColWidth)).append(" ║");
			List<String> row = i < values.size() ? values.get(i) : List.of();
			for (int j = 0; j < columnNames.size(); j++) {
				String v = j < row.size() ? row.get(j) : "";
				sb.append(" ").append(padRight(v, colWidths[j])).append(" ║");
			}
			sb.append("\n");
		}

		// Нижняя граница
		sb.append("╚").append("═".repeat(rowColWidth + 2)).append("╩");
		for (int j = 0; j < columnNames.size(); j++) {
			sb.append("═".repeat(colWidths[j] + 2));
			sb.append(j < columnNames.size() - 1 ? "╩" : "╝");
		}

		return sb.toString();
	}

	/**
	 * Форматирует значение Double с двумя знаками после запятой (Locale.ROOT).
	 * null → пустая строка.
	 */
	public static String formatValue(Double value) {
		return value == null ? "" : String.format(Locale.ROOT, "%.2f", value);
	}

	/**
	 * Дополняет строку пробелами справа до указанной длины.
	 *
	 * @param s   исходная строка (может быть null)
	 * @param len желаемая минимальная длина
	 * @return строка, дополненная пробелами справа
	 */
	private static String padRight(String s, int len) {
		String str = s == null ? "" : s;
		if (str.length() >= len) {
			return str;
		}
		return str + " ".repeat(len - str.length());
	}
}